import { motion } from "motion/react";

const fadeUp = {
  initial: { opacity: 0, y: 16 },
  whileInView: { opacity: 1, y: 0 },
  viewport: { once: true },
  transition: { duration: 0.5 },
};

export default function DPA() {
  return (
    <div className="bg-canvas-cream text-ink">
      <div className="max-w-2xl mx-auto px-6 pt-32 pb-32">
        <motion.div {...fadeUp}>
          <p className="text-eyebrow text-shade-50 mb-4">Legal</p>
          <h1 className="text-display-md text-ink mb-2">Data Processing Agreement</h1>
          <p className="text-caption text-shade-50 mb-12">Last updated: 1 April 2025. Applies to Pro and Enterprise customers.</p>

          <div className="flex flex-col gap-10">
            <section>
              <h2 className="text-heading-lg text-ink mb-4">1. Parties</h2>
              <p className="text-body-md text-shade-50">This Data Processing Agreement ("DPA") is entered into between Snapdo Technologies Pvt. Ltd. ("Processor") and the customer organization ("Controller") that has accepted Snapdo's Terms of Service.</p>
            </section>

            <section>
              <h2 className="text-heading-lg text-ink mb-4">2. Scope of processing</h2>
              <p className="text-body-md text-shade-50">The Processor will process personal data on behalf of the Controller solely for the purpose of delivering the Snapdo service: order data extraction, invoice generation, analytics, and API access. Processing is limited to what is strictly necessary for these purposes.</p>
            </section>

            <section>
              <h2 className="text-heading-lg text-ink mb-4">3. Types of personal data</h2>
              <p className="text-body-md text-shade-50">Data processed may include: business contact information, customer names and contact details submitted by the Controller, order content submitted for extraction, and transactional records generated by the service.</p>
            </section>

            <section>
              <h2 className="text-heading-lg text-ink mb-4">4. Processor obligations</h2>
              <p className="text-body-md text-shade-50 mb-3">The Processor commits to: process data only on documented Controller instructions; implement appropriate technical and organizational security measures; not engage sub-processors without Controller approval (or prior general authorization); assist the Controller in meeting data subject requests; delete or return all data upon termination of the agreement.</p>
            </section>

            <section>
              <h2 className="text-heading-lg text-ink mb-4">5. Sub-processors</h2>
              <p className="text-body-md text-shade-50">Current authorized sub-processors include: Amazon Web Services (infrastructure, India region), Razorpay (payment processing), and Postmark (transactional email). The Controller will be notified 30 days before any new sub-processor is engaged.</p>
            </section>

            <section>
              <h2 className="text-heading-lg text-ink mb-4">6. Data transfers</h2>
              <p className="text-body-md text-shade-50">All primary data processing occurs within India (AWS ap-south-1). Certain sub-processors may operate in other regions. Where data is transferred outside India, appropriate safeguards are in place per applicable data protection law.</p>
            </section>

            <section>
              <h2 className="text-heading-lg text-ink mb-4">7. Security</h2>
              <p className="text-body-md text-shade-50">The Processor maintains the security measures described in the Security page, including encryption at rest and in transit, access controls, regular audits, and incident response procedures.</p>
            </section>

            <section>
              <h2 className="text-heading-lg text-ink mb-4">8. Audit rights</h2>
              <p className="text-body-md text-shade-50">The Controller may request a summary audit report once per year at no charge. Additional audits may be arranged at the Controller's expense with 30 days notice. Enterprise customers may negotiate on-site audit rights in their contract.</p>
            </section>

            <section>
              <h2 className="text-heading-lg text-ink mb-4">9. Contact</h2>
              <p className="text-body-md text-shade-50">For DPA-related inquiries or to request a signed DPA for Enterprise use: hello.almostperfect@gmail.com</p>
            </section>
          </div>
        </motion.div>
      </div>
    </div>
  );
}
